# Generated by Django 5.1.4 on 2024-12-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_user_bio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Bio",
            new_name="bio",
        ),
    ]
