# Generated by Django 5.1.4 on 2024-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("catagory", models.CharField(max_length=50)),
                ("stock_quantity", models.IntegerField()),
                ("image_url", models.URLField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
