# Generated by Django 5.1.4 on 2024-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="catagory",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_date",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
