# Generated by Django 5.1.4 on 2024-12-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
